// Generated by CoffeeScript 1.8.0
window.LoginManager = (function() {
  function LoginManager() {}

  LoginManager.GetPage = function() {
    return ViewManager.Load("login");
  };

  LoginManager.GetConnection = function(login, password) {};

  return LoginManager;

})();
