// Generated by CoffeeScript 1.4.0
var success;

$(document).on("click", ".login-btn", function() {
  LoginManager.GetPage();
  return false;
});

success = function(data, param) {
  return alert("ok");
};

$(document).on("click", "#valid-login-input", function() {
  $.ajax({
    type: "POST",
    url: "http://localhost:8080/server/login",
    data: {
      login: $("#login-input").val(),
      password: $("#password-input").val()
    },
    success: function(msg) {
      return alert("success");
    },
    error: function(msg) {
      return alert("error");
    }
  });
  return false;
});

window.LoginManager = (function() {

  function LoginManager() {}

  LoginManager.GetPage = function() {
    return ViewManager.Load("login");
  };

  return LoginManager;

})();
