// Generated by CoffeeScript 1.8.0
var address;

address = "https://rihaninsta.herokuapp.com/";

$('#loading-image').bind('ajaxStart', function() {
  return $(this).show();
}).bind('ajaxStop', function() {
  return $(this).hide();
});

$(document).on("click", "#errorGeoaddressSubmit", function() {
  if ($("#errorGeolocation input").val() !== "") {
    return LocationManager.GetocationFromPlace($("#errorGeolocation input").val());
  }
});

window.ViewManager = (function() {
  function ViewManager() {}

  ViewManager.Init = function() {
    if ($("#header").children().length === 0) {
      $.get("./view/header.html", function(data) {
        return $("#header").html(data);
      });
    }

    /*$.get "./view/footer.html", (data) ->
    			$("#footer").html data
     */
    $.get("./view/home.html", function(data) {
      return $("#content").html(data);
    });
    return $("body").on("click", "a.viewmanager", function() {
      ViewManager.Load(this.classList[1]);
      return false;
    });
  };

  ViewManager.Load = function(pageName, args) {
    if (User.IsConnected()) {
      $("#bar-login-btn").addClass("hide");
      $("#bar-register-btn").addClass("hide");
      $("#bar-profil-btn").removeClass("hide");
    }
    if (pageName !== "home") {
      $("#header").children().remove();
    }
    $.get("./view/" + pageName + ".html", function(data) {
      return $("#content").html(data);
    });
    switch (pageName) {
      case "movie":
        return MovieManager.Init(args);
      case "location":
        return LocationManager.Init(args);
    }
  };

  return ViewManager;

})();
