// Generated by CoffeeScript 1.4.0
var address;

address = "";

$('#loading-image').bind('ajaxStart', function() {
  return $(this).show();
}).bind('ajaxStop', function() {
  return $(this).hide();
});

$(document).on("click", "#errorGeoaddressSubmit", function() {
  if ($("#errorGeolocation input").val() !== "") {
    return LocationManager.GetocationFromPlace($("#errorGeolocation input").val());
  }
});

$(document).on("click", ".login-btn", function() {
  LoginManager.GetPage();
  return false;
});

$(document).on("click", "#valid-login-input", function() {
  User.GetConnection($("#login-input").val(), $("#password-input").val());
  return false;
});

window.ViewManager = (function() {

  function ViewManager() {}

  ViewManager.Init = function() {
    if ($("#header").children().length === 0) {
      $.get("./view/header.html", function(data) {
        return $("#header").html(data);
      });
    }
    /*$.get "./view/footer.html", (data) ->
    			$("#footer").html data
    */

    $.get("./view/home.html", function(data) {
      return $("#content").html(data);
    });
    return $("body").on("click", "a.viewmanager", function() {
      ViewManager.Load(this.classList[1]);
      return false;
    });
  };

  ViewManager.Load = function(pageName, args) {
    if (pageName !== "home") {
      $("#header").children().remove();
    }
    $.get("./view/" + pageName + ".html", function(data) {
      return $("#content").html(data);
    });
    switch (pageName) {
      case "movie":
        return MovieManager.Init(args);
      case "location":
        return LocationManager.Init(args);
    }
  };

  return ViewManager;

}).call(this);
