// Generated by CoffeeScript 1.8.0
window.User = (function() {
  function User() {}

  User.latitude;

  User.longitude;

  User.pseudo;

  User.Init = function() {
    if (navigator.geolocation) {
      return navigator.geolocation.getCurrentPosition(User.GeolocSuccess, User.GeolocError, {
        timeout: 1000
      });
    } else {
      return console.err("error");
    }
  };

  User.GeolocSuccess = function(position) {
    User.latitude = position.coords.latitude;
    return User.longitude = position.coords.longitude;
  };

  User.GeolocError = function() {
    var bloc;
    $('#errorGeolocation').children().remove();
    bloc = "<div> <h1>Une erreur est survenue</h1> <h2>Nous n'avons pas réussi à vous géolocaliser.</h2> <p>Pour pouvoir continuer à utiliser notre site merci de bien vouloir entrer le nom de votre ville ou son code postal. Pour plus de précision vous pouvez également entrer une addresse. </p> <input type=\"text\" id=\"errorGeoaddress\" placeHolder=\"nom de ville, code postal, addresse, ...\"/> <div id=\"errorGeoaddressSubmit\" >Valider</div> </div>";
    $('#errorGeolocation').append(bloc);
    return $('#errorGeolocation').foundation('reveal', 'open');
  };

  User.SetLocation = function(latitude, longitude) {
    User.latitude = latitude;
    return User.longitude = longitude;
  };

  User.GetConnection = function(login, password) {
    return LoginManager.GetConnection;
  };

  User.GetPage = function() {
    return ViewManager.Load("login");
  };

  User.GetConnection = function(login, password) {
    return $.ajax({
      type: "POST",
      url: "" + address + "/user",
      data: {
        login: $("#login-input").val(),
        password: $("#password-input").val()
      },
      success: function(msg) {
        console.log(msg);
        return alert("success");
      },
      error: function(msg) {
        return alert("error");
      }
    });
  };

  return User;

})();
